### ISSUE TITLE
student + teacher buttons not redirecting

### ISSUE THREAD

**Issue by Gsirius** [Wicked-Baby/Wicked-Baby#25]

**Comment by shinsaku417** [comment]
ran up-to-date master copy on my local machine and it seems to be working. can you take a screenshot or gif on what it's looking like? also, are there any error messages in the chrome console or in the terminal?

**Comment by Gsirius** [comment]
interesting. will check again within an hour or so and let you know.

| Sasha Bayan | Composer // Singer-Songwriter // Guitarist // Sitarist|
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>

**Comment by Gsirius** [comment]
| Sasha Bayan | Composer // Singer-Songwriter // Guitarist // Sitarist|
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>

**Comment by Gsirius** [comment]
also

| Sasha Bayan | Composer // Singer-Songwriter // Guitarist // Sitarist|
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>

**Comment by Gsirius** [comment]
ok, i got it -- forgot to bower install!

| Sasha Bayan | Composer // Singer-Songwriter // Guitarist // Sitarist|
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>

**Comment by shinsaku417** [comment]
ok!
