### ISSUE TITLE
Missing student signup button, using Github Login

### ISSUE THREAD

**Issue by mccarter** [Wicked-Baby/Wicked-Baby#27]

**Comment by Gsirius** [comment]
hey Ryan - on my last merge the signup/ login button via github is on the
index.html page. Are you referring to another button or that we need a
separate page for the github button?

| Sasha Bayan | Composer // Singer-Songwriter // Guitarist // Sitarist|
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
