### ISSUE TITLE
Missing 'users' table to store usernames and salted/hashed passwords

### ISSUE THREAD

**Issue by mccarter** [Wicked-Baby/Wicked-Baby#29]

**Comment by shinsaku417** [comment]
we could use the github button that we already have and within the github authorization call back function (line 73 on server.js), we could check whether that person is a student or a teacher and generate sessions/redirect to appropriate page based on the check

**Comment by Gsirius** [comment]
definitely a sensible plan -- how are we going to distinguish between
teacher and student though? at the moment, we just have the client decide
whether they'll be a student or teacher

| Sasha Bayan | Composer // Singer-Songwriter // Guitarist // Sitarist|
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
<https://www.facebook.com/pages/Sasha-Bayan-Music/72550255824>
